require:
  - rubocop-rspec
  - rubocop-rails

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - '**/support/*.rb'

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/migrate/**.rb
    - bin/bundle

RSpec/DescribeClass:
  Exclude:
    - '**/*_rake_spec.rb'